### ISSUE TITLE
`npm run` fails with `TypeError: Cannot read properties of undefined (reading 'getOptionsDiagnostics')`

### ISSUE THREAD

**Issue by umanwizard** [korydondzila/React-TypeScript-D3#10]
Full output:

```
Starting the development server...


Could not find implementations for the following rules specified in the configuration:
    no-switch-case-fallthrough
Try upgrading TSLint and/or ensuring that you have all necessary custom rules installed.
If TSLint was recently upgraded, you may have old rules configured which need to be cleaned up.
        
Warning: The 'no-unused-variable' rule requires type checking
ts-loader: Using typescript@4.9.5 and /home/brennan/code/React-TypeScript-D3/tsconfig.json
/home/brennan/code/React-TypeScript-D3/node_modules/typescript/lib/typescript.js:169553
            return __spreadArray(__spreadArray([], program.getOptionsDiagnostics(cancellationToken), true), program.getGlobalDiagnostics(cancellationToken), true);
                                                           ^

TypeError: Cannot read properties of undefined (reading 'getOptionsDiagnostics')
    at Object.getCompilerOptionsDiagnostics (/home/brennan/code/React-TypeScript-D3/node_modules/typescript/lib/typescript.js:169553:60)
    at provideCompilerOptionDiagnosticErrorsToWebpack (/home/brennan/code/React-TypeScript-D3/node_modules/ts-loader/dist/after-compile.js:34:92)
    at Compiler.<anonymous> (/home/brennan/code/React-TypeScript-D3/node_modules/ts-loader/dist/after-compile.js:15:9)
    at next (/home/brennan/code/React-TypeScript-D3/node_modules/tapable/lib/Tapable.js:140:14)
    at Compiler.<anonymous> (/home/brennan/code/React-TypeScript-D3/node_modules/webpack/lib/CachePlugin.js:62:5)
    at Compiler.applyPluginsAsyncSeries (/home/brennan/code/React-TypeScript-D3/node_modules/tapable/lib/Tapable.js:142:13)
    at /home/brennan/code/React-TypeScript-D3/node_modules/webpack/lib/Compiler.js:496:10
    at Compilation.applyPluginsAsyncSeries (/home/brennan/code/React-TypeScript-D3/node_modules/tapable/lib/Tapable.js:131:46)
    at /home/brennan/code/React-TypeScript-D3/node_modules/webpack/lib/Compilation.js:649:19
    at Compilation.applyPluginsAsyncSeries (/home/brennan/code/React-TypeScript-D3/node_modules/tapable/lib/Tapable.js:131:46)
    at /home/brennan/code/React-TypeScript-D3/node_modules/webpack/lib/Compilation.js:640:11
    at Compilation.applyPluginsAsyncSeries (/home/brennan/code/React-TypeScript-D3/node_modules/tapable/lib/Tapable.js:131:46)
    at /home/brennan/code/React-TypeScript-D3/node_modules/webpack/lib/Compilation.js:635:10
    at Compilation.applyPluginsAsyncSeries (/home/brennan/code/React-TypeScript-D3/node_modules/tapable/lib/Tapable.js:131:46)
    at sealPart2 (/home/brennan/code/React-TypeScript-D3/node_modules/webpack/lib/Compilation.js:631:9)
    at Compilation.applyPluginsAsyncSeries (/home/brennan/code/React-TypeScript-D3/node_modules/tapable/lib/Tapable.js:131:46)
```

**Comment by korydondzila** [comment]
My code and post for this are about 6 years old, I know there was major breaking changes to D3 apparently a few years ago. I won't be updating this for any fixes, as I would likely need a rewrite, but will archive the repo.
